language: cpp

sudo: required
dist: trusty

install:
   - sudo apt-get install libgtest-dev

compiler:
- gcc

os:
- linux

before_script:
 - cmake -DTARGET_HARDWARE=PC -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_COMPILER=c++

script: make
