language: cpp

sudo: required
dist: trusty

install:
   - sudo apt-get install libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake CMakeLists.txt
   - sudo make
   - sudo cp *.a /usr/lib

compiler:
- gcc

os:
- linux

before_script:
 - cmake -DTARGET_HARDWARE=PC -DCMAKE_CXX_COMPILER=c++

script: make
